echo Executing NeXTTool to upload ../../../nxtOSEK/ecrobot/../ecrobot/bios/nxt_bios_rom.rfw...
 /Users/e125754/etrobo/nxtOSEK/nexttool/nexttool /COM=usb -firmware=../../../nxtOSEK/ecrobot/../ecrobot/bios/nxt_bios_rom.rfw
